server:
  port: 9999

spring:
  #上传文件的大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/music
    username: root
    password: 123456
  redis:
    host: localhost
    database: 0
    port: 6379
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
    # cache 缓存配置内容
  cache:
    type: redis


# 文件存放路径
filePath: 'D:\project\file\'

# 关闭springboot多余的启动日志
logging:
  level:
    root: off
    org:
      springframework: off


